# Generated by Django 3.1 on 2021-11-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('general', 'General enquiry'), ('bug', 'Bug report'), ('suggestion', 'Suggestion')], max_length=40)),
                ('message', models.CharField(max_length=200)),
                ('sender', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
