# Generated by Django 4.1.4 on 2023-08-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yvfoundation', '0002_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='topic',
            field=models.CharField(choices=[('general', 'General enquiry'), ('suggestion', 'Suggestion'), ('bug', 'Bug report')], max_length=40),
        ),
    ]
