# Generated by Django 4.1.4 on 2023-08-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yvfoundation', '0003_alter_contact_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='topic',
            field=models.CharField(choices=[('general', 'General enquiry'), ('suggestion', 'Suggestion')], max_length=40),
        ),
    ]
